name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build_matrix:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php_version: [8.4.0]
        mode: [normal, leak]
    name: PHP ${{ matrix.php_version }} - ${{ matrix.mode }}

    steps:
      - name: 🔄 Checkout repository
        uses: actions/checkout@v3

      - name: 💾 Cache compiled PHP
        id: cache-php
        uses: actions/cache@v3
        with:
          path: ./php-install
          key: php-${{ matrix.php_version }}-build

      - name: 🧰 Install required dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential autoconf libtool \
            php-dev php-pear \
            g++ pkg-config \
            libopenblas-dev libgomp1 wget valgrind

      - name: 🐘 Compile PHP (only if not cached)
        if: steps.cache-php.outputs.cache-hit != 'true'
        run: |
          mkdir -p php-src
          cd php-src
          wget -O php.tar.gz https://www.php.net/distributions/php-${{ matrix.php_version }}.tar.gz
          tar -xf php.tar.gz --strip-components=1
          ./configure \
            --prefix=$GITHUB_WORKSPACE/php-install \
            --with-config-file-path=$GITHUB_WORKSPACE/php-install/etc \
            --enable-debug
          make -j$(nproc)
          make install

      - name: 🧭 Add PHP to PATH
        run: echo "${{ github.workspace }}/php-install/bin" >> $GITHUB_PATH

      - name: 🔧 Build ZMatrix extension
        run: |
          cd ${{ github.workspace }}
          phpize

          if [ "${{ matrix.mode }}" = "leak" ]; then
            export CFLAGS="-fsanitize=address -g -O1"
            export CXXFLAGS="-fsanitize=address -g -O1"
          fi

          ./configure
          make -j$(nproc)
          make install

          mkdir -p $GITHUB_WORKSPACE/php-install/etc/conf.d
          echo "extension=zmatrix.so" > $GITHUB_WORKSPACE/php-install/etc/conf.d/zmatrix.ini

      - name: 🧪 Run tests
        continue-on-error: true
        run: |
          export USE_ZEND_ALLOC=0

          if [ "${{ matrix.mode }}" = "leak" ]; then
            echo "🧠 Running tests with Valgrind..."
            valgrind --leak-check=full --show-leak-kinds=all \
              --track-origins=yes --error-exitcode=1 \
              --log-file=valgrind.log \
                php tests/basic.phpt || exit 1
          else
            echo "🧪 Running normal tests..."
            make test TEST_PHP_EXECUTABLE="$GITHUB_WORKSPACE/php-install/bin/php -dextension=zmatrix.so"
          fi

          if [ -d tests/.tphp ]; then
            for test_file in tests/.tphp/*.tphp; do
              echo "▶️ Running $test_file..."
              php "$test_file" || exit 1
            done
          fi

      - name: 📄 Show make test output
        if: always()
        run: cat php_test_results_*.txt || echo "No report available"

      - name: 🧠 Show Valgrind log (if leak mode)
        if: matrix.mode == 'leak' && always()
        run: cat valgrind.log || echo "No Valgrind output"

      - name: 🎨 Code Formatting
        run: |
          # Verifica se o código está formatado corretamente
          find . -name "*.[ch]pp" -print0 | xargs -0 clang-format -n -Werror
      
          # (Opcional) Formata o código automaticamente
          # find . -name "*.[ch]pp" -print0 | xargs -0 clang-format -i
          
      - name: 🔍 Static Analysis (cppcheck)
        run: |
          cppcheck --enable=all --suppress=missingIncludeSystem ${{ github.workspace }}
